### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by detectingdragon77** [cnlohr/channel3#10]

**Comment by doggukan** [comment]
Yes we need a guide for beginners.

**Comment by doggukan** [comment]
Just flash the binaries it will work.for me i used nodemcu flasher selected 2 bin files and burned them.

**Comment by cnlohr** [comment]
Just closing out old issues. If you configure your build environment in line with https://github.com/cnlohr/esp82xx it should compile with "make" but you will need Linux or OSX.
