### ISSUE TITLE
I live in a PAL country. Could this work with PAL?

### ISSUE THREAD

**Issue by bootrino** [cnlohr/channel3#14]

**Comment by cnlohr** [comment]
you would need to change a number of constants to change the lines etc.  And you'd need to change the code to synth the signal but neither are too hard.  Check out the video to get a feel for how to use the web interface and you can do a number of tests that way.

**Comment by Duality4Y** [comment]
so i have this portable tv but it's pall and i am trying to find where to change the lines, any pointers? i am looking in ntsc_broadcast but i am not really finding anything related to that.

**Comment by Duality4Y** [comment]
ok this is way to complicated for me :D i adjusted the number of lines for pal, it's sharper now. so i'll have to live with it being in black and white for now :)

**Comment by cnlohr** [comment]
I am shocked your TV was willing to tolerate that at all!

But, the other stuff you will have to tweak is in the table make for the frequency synthesizer -- it's one of the tools that runs that makes a table for the ESP.
