### ISSUE TITLE
Have you tried this on an ESP32?

### ISSUE THREAD

**Issue by bootrino** [cnlohr/channel3#16]
Does this work on an Arduino ESP32?

**Comment by cnlohr** [comment]
The mechanism should work, but most of the project would need to be rewritten :(

**Comment by bootrino** [comment]
That's a pity.  Would ESP32 allow any great new features beyond current version?

**Comment by cnlohr** [comment]
Sort of, it would allow a ton more CPU time to do stuff.

**Comment by zombodotcom** [comment]
maybe someone could make one that does the CPU work on one esp32 and displaying through wifi or ble on the other

**Comment by imranaalam** [comment]
May be bitluni and cnlohr project be used in parts. 
Where to look for in the code to convert composite video to RF signal on RX and I2S pins in your code?
