### ISSUE TITLE
Broadcasting POCSAG over VHF?

### ISSUE THREAD

**Issue by gr01d** [cnlohr/channel3#19]
Can esp8266 be reprogrammed to broadcast POCSAG messages over 169.7000MHz VHF?
For the raspberry pi this is the project: https://github.com/F5OEO/rpitx

**Comment by donBuba** [comment]
no, it can't, because the i2s peripherals allow a max of 80mhz.

**Comment by gr01d** [comment]
thanks

**Comment by cnlohr** [comment]
It is _technically_ possible to transmit very weak signals at that.  There is a very small amount of energy left, despite the 80 MHz bit rate.  Remember 62.5 MHz is ABOVE the maximum of 40 MHz this system can make.  It's just that the emitted frequencies mirror AROUND that 40 MHz.
