### ISSUE TITLE
Audio?

### ISSUE THREAD

**Issue by vespakoen** [cnlohr/channel3#4]
Is is possible to send audio to an old tv box?
Would be a cool way to give these things a second life (radio + visualisations) =)

**Comment by cnlohr** [comment]
If you ditch color, it is entirelly possible to find another divisor (not 1408) that would accomidate both channel 3 video and the audio carrier band.  Well, you'd need two audio carriers... but it should be possible, I'm probably not the person to do it.

**Comment by cnlohr** [comment]
(Closing issue until someone else takes it on)
